export default function Head() {
  return (
    <>
      <title>CrunchyRoll</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="https://static.crunchyroll.com/cr-spa-registration/assets/img/favicons/favicon-16x16.png"
            data-react-helmet="true"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="https://static.crunchyroll.com/cr-spa-registration/assets/img/favicons/favicon-32x32.png"
            data-react-helmet="true"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="96x96"
            href="https://static.crunchyroll.com/cr-spa-registration/assets/img/favicons/favicon-96x96.png"
            data-react-helmet="true"
          />
    </>
  )
}
